package com.nexus.nexusiam.domain.model;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_CREATED,
    USER_DELETED,
    USER_DEACTIVATED,

    ORG_CREATED,
    ORG_UPDATED,
    ORG_DELETED,

    TEAM_CREATED,
    TEAM_UPDATED,
    TEAM_DELETED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,

    API_CLIENT_REGISTERED,
    API_CLIENT_TOKEN_ISSUED,
    API_CLIENT_DEACTIVATED,
    API_CLIENT_DELETED
}
