server:
  port: 8080

spring:
  application:
    name: nexus-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/nexus
    username: nexus
    password: nexus_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379





nexus:
  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 900000
      refresh-expiration: 604800000

logging:
  level:
    com.nexus: DEBUG
    org.springframework: WARN
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG



springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true