server:
  port: 8080

spring:
  application:
    name: nexus-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/nexus
    username: nexus
    password: nexus_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  elasticsearch:
    uris: http://localhost:9200
    restclient:
      ssl:
        enabled: false



nexus:
  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

logging:
  level:
#    com.nexus: INFO
    com.nexus: DEBUG
    org.springframework: WARN
    org.flywaydb: DEBUG



management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true